apiVersion: apps/v1
kind: Deployment

metadata:
  name: product-service
  namespace: shopstream

spec:
  replicas: 1

  selector:
    matchLabels:
      app: product-service

  template:
    metadata:
      labels:
        app: product-service

    spec:
      containers:
        - name: product-service
          image: sentinel/product-service:dev
          imagePullPolicy: Never

          ports:
            - containerPort: 8000

